### ISSUE TITLE
Error in groupby().first()

### ISSUE THREAD

**Issue by capelastegui** [sky-uk/anticipy#152]
In forecast.run_forecast_single():

```
    # Determine best fits
    df_best_fit = (
        df_metadata.loc[df_metadata.is_fit]
        .sort_values('aic_c')
        .groupby('source', as_index=False)
        .first()[['source_long', 'model']]
    )
```

After updating to pandas 1.0.0, this raises a ValueError:
```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()<<<<<
```

This is due to the fact that we are calling groupby.first() on a dataframe with a column that contains arrays. In hindsight, that may not have been the wisest of choices. The following code replicates the bug:

```
df = pd.DataFrame(data=dict(c1='A',c2=[np.array([1,2]),np.array([2])]))
df.groupby('c1', as_index=False).first() # This raises a ValueError
```

Solution may be as easy as using lists instead of arrays:

```
df = pd.DataFrame(data=dict(c1='A',c2=[[1,2],[2]]))
df.groupby('c1', as_index=False).first() # This works
```

**Comment by capelastegui** [comment]
Ok, it was easier than that - the column with the array was being dropped right after groupby.first()... so if we move things around, it works.

**Comment by bezes** [comment]
There was a simpler solution: I've seen that replacing .first() with .nth(0) fixed the bug.

**Comment by capelastegui** [comment]
Good to know, in case this ever comes up again when we can't drop the columns.
