### ISSUE TITLE
FutureWarning when importing pandas

### ISSUE THREAD

**Issue by capelastegui** [sky-uk/anticipy#163]
```
FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
```

This is raised when checking for datetime data type:
```python
if isinstance(date_start_actuals, pd.datetime):
```

**Comment by maulberto3** [comment]
Hi @capelastegui, I can assert this warning is still showing.

**Comment by capelastegui** [comment]
Yes, the fix is on the development branch, and it's been a while since the last release. I'll try to push out a new release soon.

**Comment by capelastegui** [comment]
Release 0.1.8 fixes this.
