### ISSUE TITLE
Add readthedocs support 

### ISSUE THREAD

**Issue by ibegleris** [sky-uk/anticipy#33]
When the repository becomes open source we will have access to readthedocs. We should implement the "build docs" feature in to the repository and link the github pages to readthedocs for documentation.

**Comment by capelastegui** [comment]
Readthedocs has been set up for the project. Docs available in:

https://readthedocs.org/projects/anticipy/

Before closing the issue, we need to fully migrate the docs from GitHub pages:
- Change the docs link in README.md to point to readthedocs
- Remove gh-pages branch
- we should probably change, in docs/Makefile, line 4:  BUILDDIR =build

**Comment by ibegleris** [comment]
#

**Comment by ibegleris** [comment]
Fixed in previous commita
